apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app
  namespace: argocd
spec:
  description: Project for the app service
  clusterResourceWhitelist:
    - group: ""
      kind: "Namespace"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://github.com/jwasz/chart-demo
  destinations:
    - server: https://kubernetes.default.svc
      namespace: app-*
